
import type { Equipment } from './types';
import { format } from 'date-fns';

const today = new Date();
const todayFormatted = format(today, 'yyyy-MM-dd');
const nextMaintenanceDate = format(new Date(new Date().setMonth(new Date().getMonth() + 3)), 'yyyy-MM-dd');

// This file is ready for future data seeding.
// To add new equipment, populate this array following the example structure.
export const equipmentToSeed: Array<Omit<Equipment, 'id' | 'vsdId' | 'status' > & { model: string; serialNumber: string, installationDate: string, driveType?: 'VSD' | 'Soft Starter', manufacturer?: string }> = [
    { name: 'Pump 19A', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS880', serialNumber: 'FPC-001', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 19B', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS880', serialNumber: 'FPC-002', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 19C', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS880', serialNumber: 'FPC-003', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 34B', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS800', serialNumber: 'FPC-004', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 34D', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS800', serialNumber: 'FPC-005', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 34F', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS800', serialNumber: 'FPC-006', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 35B', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS800', serialNumber: 'FPC-007', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 35F', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS800', serialNumber: 'FPC-008', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 35K', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS800', serialNumber: 'FPC-009', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 42', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'Siemens', model: 'Masterdrive', serialNumber: 'FPC-010', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 42', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'Siemens', model: 'Masterdrive', serialNumber: 'FPC-011', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 41', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'Siemens', model: 'Masterdrive', serialNumber: 'FPC-012', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 41', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'Siemens', model: 'Masterdrive', serialNumber: 'FPC-013', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 40', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'Siemens', model: 'Masterdrive', serialNumber: 'FPC-014', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 40', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'Siemens', model: 'Masterdrive', serialNumber: 'FPC-015', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Conveyor 48B', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS880', serialNumber: 'FPC-016', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Conveyor 48A', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS880', serialNumber: 'FPC-017', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 6', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'Siemens', model: 'Masterdrive', serialNumber: 'FPC-018', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Conveyor 47', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'ABB', model: 'ACS800', serialNumber: 'FPC-019', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 32C (Sump 32)', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'Siemens', model: 'Micromaster 440', serialNumber: 'FPC-020', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 33C (Sump 32)', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'Siemens', model: 'Micromaster 440', serialNumber: 'FPC-021', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'WIMS cleaner 4', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'VSD', manufacturer: 'Siemens', model: 'Simoreg DC', serialNumber: 'FPC-022', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 24C RFS Transfer Pump', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'Soft Starter', manufacturer: 'Allen-Bradley SMC-Flex', model: 'SMC-FLEX', serialNumber: 'FPC-023', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 43', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'Soft Starter', manufacturer: 'Allen-Bradley SMC-Flex', model: 'SMC-FLEX', serialNumber: 'FPC-024', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 44', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'Soft Starter', manufacturer: 'Allen-Bradley SMC-Flex', model: 'SMC-FLEX', serialNumber: 'FPC-025', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 45', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'Soft Starter', manufacturer: 'Allen-Bradley SMC-Flex', model: 'SMC-FLEX', serialNumber: 'FPC-026', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 34 A', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'Soft Starter', manufacturer: 'Natronics', model: 'TC900', serialNumber: 'FPC-027', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 34 C', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'Soft Starter', manufacturer: 'Natronics', model: 'TC900', serialNumber: 'FPC-028', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 34 E', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'Soft Starter', manufacturer: 'Allen-Bradley', model: 'SMC-FLEX', serialNumber: 'FPC-029', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 35A', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'Soft Starter', manufacturer: 'Phasecon', model: 'SF6000', serialNumber: 'FPC-030', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 35E', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'Soft Starter', manufacturer: 'Phasecon', model: 'SF6000', serialNumber: 'FPC-031', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
    { name: 'Pump 35 J', plant: 'Smelter', division: 'MSP', location: 'MSP - FPC', driveType: 'Soft Starter', manufacturer: 'Allen-Bradley SMC-Flex', model: 'SMC-FLEX', serialNumber: 'FPC-032', installationDate: todayFormatted, lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate },
];
