
import type { Equipment } from './types';
import { format } from 'date-fns';

const today = new Date();
const todayFormatted = format(today, 'yyyy-MM-dd');
const nextMaintenanceDate = format(new Date(new Date().setMonth(new Date().getMonth() + 3)), 'yyyy-MM-dd');

// This file is ready for future data seeding.
// To add new equipment, populate this array following the example structure.
export const pumpStations: Array<Omit<Equipment, 'id' | 'vsdId' | 'status' > & { model: string; serialNumber: string, installationDate: string }> = [
    { name: 'RTR 1A (Feeder)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-1A', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 1B (Drum)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-1B', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 2A (Feeder)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-2A', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 2B (Drum)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-2B', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 3A (Feeder)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-3A', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 3B (Drum)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-3B', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 4A (Feeder)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-4A', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 4B (Drum)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-4B', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 5A (Feeder)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-5A', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 5B (Drum)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-5B', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 6A (Feeder)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-6A', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 6B (Drum)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-6B', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 7A (Feeder)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-7A', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 7B (Drum)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-7B', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 8A (Feeder)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-8A', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'RTR 8B (Drum)', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-8B', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'Weigh Feeder', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-WF', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
    { name: 'Hammer Sampler', location: 'Roaster - RTR Magnets', plant: 'Smelter', division: 'Roaster', lastMaintenance: todayFormatted, nextMaintenance: nextMaintenanceDate, model: 'Siemens Micromaster 440', serialNumber: 'TBD-RTR-HS', installationDate: todayFormatted, uptime: 100, powerConsumption: 0 },
];
