
import type { Equipment, VSD } from './types';
import { format } from 'date-fns';
import { collection, writeBatch, doc } from 'firebase/firestore';

const today = new Date();
const installationDate = format(new Date('2023-01-01'), "yyyy-MM-dd");

export const seedEquipment: Equipment[] = [
    // Hlabane
    {
        id: "ps-hlabane-pump-01",
        name: "Hlabane Pump No.1",
        type: "Pump",
        location: "HLABANE",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-ps-hlabane-pump-01",
        model: "ABB ACS 880",
        serialNumber: "SN-PS-HLB-01",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.8,
        powerConsumption: 45000,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "ps-hlabane-pump-02",
        name: "Hlabane Pump No.2",
        type: "Pump",
        location: "HLABANE",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-ps-hlabane-pump-02",
        model: "ABB ACS 880",
        serialNumber: "SN-PS-HLB-02",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.5,
        powerConsumption: 52000,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "ps-hlabane-pump-03",
        name: "Hlabane Pump No.3",
        type: "Pump",
        location: "HLABANE",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-ps-hlabane-pump-03",
        model: "ABB ACS 880",
        serialNumber: "SN-PS-HLB-03",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.7,
        powerConsumption: 46000,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "ps-hlabane-pump-04",
        name: "Hlabane Pump No.4",
        type: "Pump",
        location: "HLABANE",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-ps-hlabane-pump-04",
        model: "ABB ACS 880",
        serialNumber: "SN-PS-HLB-04",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.6,
        powerConsumption: 53000,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "ps-hlabane-pump-05",
        name: "Hlabane Pump No.5",
        type: "Pump",
        location: "HLABANE",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-ps-hlabane-pump-05",
        model: "ABB ACS 880",
        serialNumber: "SN-PS-HLB-05",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.8,
        powerConsumption: 45500,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "ps-hlabane-pump-06",
        name: "Hlabane Pump No.6",
        type: "Pump",
        location: "HLABANE",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-ps-hlabane-pump-06",
        model: "ABB ACS 880",
        serialNumber: "SN-PS-HLB-06",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.4,
        powerConsumption: 52500,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "ps-hlabane-pump-07",
        name: "Hlabane Pump No.7",
        type: "Pump",
        location: "HLABANE",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-ps-hlabane-pump-07",
        model: "ABB ACS 880",
        serialNumber: "SN-PS-HLB-07",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.9,
        powerConsumption: 44000,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "ps-hlabane-pump-08",
        name: "Hlabane Pump No.8",
        type: "Pump",
        location: "HLABANE",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-ps-hlabane-pump-08",
        model: "ABB ACS 880",
        serialNumber: "SN-PS-HLB-08",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.7,
        powerConsumption: 47000,
        assignedToId: '',
        assignedToName: '',
    },
    // Mposa Pump Station
    {
        id: "mps-pump-set1-stage1",
        name: "Mposa Pump Set 1 - Stage 1",
        type: "Pump",
        location: "Mposa Pump Station",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-mps-ps1-s1",
        model: "Schneider ALTISTART 48 S/S",
        serialNumber: "SN-MPS-PS1-S1",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.9,
        powerConsumption: 32000,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "mps-pump-set1-stage2",
        name: "Mposa Pump Set 1 - Stage 2",
        type: "Pump",
        location: "Mposa Pump Station",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-mps-ps1-s2",
        model: "Schneider ALTISTART 48 S/S",
        serialNumber: "SN-MPS-PS1-S2",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.8,
        powerConsumption: 33000,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "mps-pump-set2-stage1",
        name: "Mposa Pump Set 2 - Stage 1",
        type: "Pump",
        location: "Mposa Pump Station",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-mps-ps2-s1",
        model: "Schneider ALTISTART 48 S/S",
        serialNumber: "SN-MPS-PS2-S1",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.7,
        powerConsumption: 32500,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "mps-pump-set2-stage2",
        name: "Mposa Pump Set 2 - Stage 2",
        type: "Pump",
        location: "Mposa Pump Station",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-mps-ps2-s2",
        model: "Schneider ALTISTART 48 S/S",
        serialNumber: "SN-MPS-PS2-S2",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.9,
        powerConsumption: 34000,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "mps-pump-set3-stage1",
        name: "Mposa Pump Set 3 - Stage 1",
        type: "Pump",
        location: "Mposa Pump Station",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-mps-ps3-s1",
        model: "Schneider ALTISTART 48 S/S",
        serialNumber: "SN-MPS-PS3-S1",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.6,
        powerConsumption: 31000,
        assignedToId: '',
        assignedToName: '',
    },
    {
        id: "mps-pump-set3-stage2",
        name: "Mposa Pump Set 3 - Stage 2",
        type: "Pump",
        location: "Mposa Pump Station",
        plant: "Mining",
        division: "Pump Stations",
        vsdId: "vsd-mps-ps3-s2",
        model: "Schneider ALTISTART 48 S/S",
        serialNumber: "SN-MPS-PS3-S2",
        status: "active",
        installationDate: installationDate,
        lastMaintenance: format(today, "yyyy-MM-dd"),
        nextMaintenance: format(new Date(new Date().setMonth(today.getMonth() + 3)), "yyyy-MM-dd"),
        uptime: 99.8,
        powerConsumption: 31500,
        assignedToId: '',
        assignedToName: '',
    },
];


export const seedVsds: VSD[] = seedEquipment.map(eq => ({
    id: eq.vsdId,
    serialNumber: eq.serialNumber,
    equipmentId: eq.id,
    model: eq.model,
    installationDate: eq.installationDate,
    status: eq.status,
    assignedToId: eq.assignedToId || '',
    assignedToName: eq.assignedToName || '',
}));


export async function seedDatabase(firestore: any) {

  const batch = writeBatch(firestore);

  const equipmentCollection = collection(firestore, 'equipment');
  seedEquipment.forEach(equipmentDoc => {
    const { id, ...data } = equipmentDoc;
    const docRef = doc(equipmentCollection, id);
    batch.set(docRef, data);
  });

  const vsdCollection = collection(firestore, 'vsds');
  seedVsds.forEach(vsdDoc => {
    const { id, ...data } = vsdDoc;
    const docRef = doc(vsdCollection, id);
    batch.set(docRef, data);
  });

  try {
    await batch.commit();
    alert('New pump station equipment data has been successfully seeded!');
  } catch (error) {
    console.error('Error seeding data: ', error);
    alert('An error occurred while seeding the data. Check the console for details.');
  }
}
