const fs = require('fs');
const filePath = 'src/app/reports/history/page.tsx';

let content = fs.readFileSync(filePath, 'utf8');

// Update imports
content = content.replace(
    "import { FileText, Loader2 } from 'lucide-react';",
    "import { FileText, Loader2, Trash2 } from 'lucide-react';"
);

content = content.replace(
    "import { useCollection, useFirestore, useMemoFirebase } from '@/firebase';",
    "import { useCollection, useFirestore, useMemoFirebase, useUser, useDoc, deleteDocumentNonBlocking } from '@/firebase';\nimport { doc } from 'firebase/firestore';\nimport type { User } from '@/lib/types';\nimport { useToast } from '@/hooks/use-toast';\nimport {\n  AlertDialog,\n  AlertDialogAction,\n  AlertDialogCancel,\n  AlertDialogContent,\n  AlertDialogDescription,\n  AlertDialogFooter,\n  AlertDialogHeader,\n  AlertDialogTitle,\n  AlertDialogTrigger,\n} from \"@/components/ui/alert-dialog\";"
);

content = content.replace(
    "import { collection, orderBy, query } from 'firebase/firestore';",
    "import { collection, orderBy, query } from 'firebase/firestore';" // leave it
);

// We need to remove the duplicate `import { doc } from 'firebase/firestore'` but it's fine if we just imported it earlier, wait no it's not imported there.
// Actually let's just rewrite the whole file cleanly.

const newFileContent = `
'use client';

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { FileText, Loader2, Trash2 } from 'lucide-react';
import Link from 'next/link';
import { useCollection, useFirestore, useMemoFirebase, useUser, useDoc, deleteDocumentNonBlocking } from '@/firebase';
import { collection, orderBy, query, doc } from 'firebase/firestore';
import type { GeneratedReport, User } from '@/lib/types';
import { format, isValid } from 'date-fns';
import { useToast } from '@/hooks/use-toast';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

export default function ReportHistoryPage() {
    const firestore = useFirestore();
    const { user } = useUser();
    const { toast } = useToast();

    const userRoleRef = useMemoFirebase(() => (user ? doc(firestore, 'users', user.uid) : null), [firestore, user]);
    const { data: currentUserData } = useDoc<User>(userRoleRef);
    const canDelete = currentUserData?.role === 'Admin' || currentUserData?.role === 'Superadmin';

    const reportsQuery = useMemoFirebase(() =>
        query(collection(firestore, 'generated_reports'), orderBy('generatedAt', 'desc')),
        [firestore]
    );

    const { data: reports, isLoading } = useCollection<GeneratedReport>(reportsQuery);

    const formatDate = (timestamp: any) => {
        if (!timestamp) return 'N/A';
        try {
            const date = timestamp.seconds ? new Date(timestamp.seconds * 1000) : new Date(timestamp);
            if (!isValid(date)) return 'Invalid Date';
            return format(date, 'yyyy-MM-dd HH:mm');
        } catch {
            return 'Invalid Date';
        }
    }

    const handleDelete = (reportId: string) => {
        if (!reportId) return;
        deleteDocumentNonBlocking(doc(firestore, 'generated_reports', reportId));
        toast({ title: 'Report Deleted', description: 'The report has been permanently removed.' });
    };

    return (
        <div className="flex flex-col gap-8">
            <header>
                <h1 className="text-3xl font-bold tracking-tight">AI Report History</h1>
                <p className="text-muted-foreground">
                    A log of all previously generated and saved AI reports.
                </p>
            </header>
            <Card>
                <CardHeader>
                    <CardTitle>Saved Reports</CardTitle>
                    <CardDescription>View past reports generated by the AI.</CardDescription>
                </CardHeader>
                <CardContent>
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Generated At</TableHead>
                                <TableHead>Report Period</TableHead>
                                <TableHead>Generated By</TableHead>
                                <TableHead className="text-right">Actions</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {isLoading ? (
                                <TableRow>
                                    <TableCell colSpan={4} className="h-24 text-center">
                                        <div className="flex justify-center items-center">
                                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                            Loading report history...
                                        </div>
                                    </TableCell>
                                </TableRow>
                            ) : reports && reports.length > 0 ? (
                                reports.map(report => (
                                    <TableRow key={report.id}>
                                        <TableCell>{formatDate(report.generatedAt)}</TableCell>
                                        <TableCell>{report.startDate} to {report.endDate}</TableCell>
                                        <TableCell>{report.generatedByUserName}</TableCell>
                                        <TableCell className="text-right flex items-center justify-end gap-2">
                                            <Link href={\`/reports/history/\${report.id}\`} passHref>
                                                <Button variant="ghost" size="icon">
                                                    <FileText className="h-4 w-4" />
                                                    <span className="sr-only">View Report</span>
                                                </Button>
                                            </Link>
                                            {canDelete && (
                                                <AlertDialog>
                                                    <AlertDialogTrigger asChild>
                                                        <Button variant="ghost" size="icon" className="text-destructive hover:text-destructive/80 hover:bg-destructive/10">
                                                            <Trash2 className="h-4 w-4" />
                                                            <span className="sr-only">Delete Report</span>
                                                        </Button>
                                                    </AlertDialogTrigger>
                                                    <AlertDialogContent>
                                                        <AlertDialogHeader>
                                                            <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                                                            <AlertDialogDescription>
                                                                This action cannot be undone. This will permanently delete the saved report from the database.
                                                            </AlertDialogDescription>
                                                        </AlertDialogHeader>
                                                        <AlertDialogFooter>
                                                            <AlertDialogCancel>Cancel</AlertDialogCancel>
                                                            <AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={() => handleDelete(report.id)}>
                                                                Delete
                                                            </AlertDialogAction>
                                                        </AlertDialogFooter>
                                                    </AlertDialogContent>
                                                </AlertDialog>
                                            )}
                                        </TableCell>
                                    </TableRow>
                                ))
                            ) : (
                                <TableRow>
                                    <TableCell colSpan={4} className="text-center h-24">
                                        No saved reports found.
                                    </TableCell>
                                </TableRow>
                            )}
                        </TableBody>
                    </Table>
                </CardContent>
            </Card>
        </div>
    );
}
`;

fs.writeFileSync(filePath, newFileContent, 'utf8');
console.log("Updated history page");
