'use client';

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { FileText, Loader2 } from 'lucide-react';
import Link from 'next/link';
import { useCollection, useFirestore, useMemoFirebase } from '@/firebase';
import { collection, orderBy, query } from 'firebase/firestore';
import type { GeneratedReport } from '@/lib/types';
import { format } from 'date-fns';

export default function ReportHistoryPage() {
    const firestore = useFirestore();

    const reportsQuery = useMemoFirebase(() =>
        query(collection(firestore, 'generated_reports'), orderBy('generatedAt', 'desc')),
        [firestore]
    );

    const { data: reports, isLoading } = useCollection<GeneratedReport>(reportsQuery);

    const formatDate = (timestamp: any) => {
        if (!timestamp) return 'N/A';
        // Firestore timestamps can be either objects with seconds/nanoseconds or already dates.
        if (timestamp.seconds) {
            return format(new Date(timestamp.seconds * 1000), 'yyyy-MM-dd HH:mm');
        }
        try {
            return format(new Date(timestamp), 'yyyy-MM-dd HH:mm');
        } catch {
            return 'Invalid Date';
        }
    }

    return (
        <div className="flex flex-col gap-8">
            <header>
                <h1 className="text-3xl font-bold tracking-tight">AI Report History</h1>
                <p className="text-muted-foreground">
                    A log of all previously generated and saved AI reports.
                </p>
            </header>
            <Card>
                <CardHeader>
                    <CardTitle>Saved Reports</CardTitle>
                    <CardDescription>View past reports generated by the AI.</CardDescription>
                </CardHeader>
                <CardContent>
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Generated At</TableHead>
                                <TableHead>Report Period</TableHead>
                                <TableHead>Generated By</TableHead>
                                <TableHead className="text-right">Actions</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {isLoading ? (
                                <TableRow>
                                    <TableCell colSpan={4} className="h-24 text-center">
                                        <div className="flex justify-center items-center">
                                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                            Loading report history...
                                        </div>
                                    </TableCell>
                                </TableRow>
                            ) : reports && reports.length > 0 ? (
                                reports.map(report => (
                                    <TableRow key={report.id}>
                                        <TableCell>{formatDate(report.generatedAt)}</TableCell>
                                        <TableCell>{report.startDate} to {report.endDate}</TableCell>
                                        <TableCell>{report.generatedByUserName}</TableCell>
                                        <TableCell className="text-right">
                                            <Link href={`/reports/history/${report.id}`} passHref>
                                                <Button variant="ghost" size="icon">
                                                    <FileText className="h-4 w-4" />
                                                    <span className="sr-only">View Report</span>
                                                </Button>
                                            </Link>
                                        </TableCell>
                                    </TableRow>
                                ))
                            ) : (
                                <TableRow>
                                    <TableCell colSpan={4} className="h-24 text-center">
                                        No saved reports found.
                                    </TableCell>
                                </TableRow>
                            )}
                        </TableBody>
                    </Table>
                </CardContent>
            </Card>
        </div>
    );
}
