'use client';

import { useParams, notFound, useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Loader2, ArrowLeft, Printer } from 'lucide-react';
import { useDoc, useFirestore, useMemoFirebase } from '@/firebase';
import { doc } from 'firebase/firestore';
import type { GeneratedReport } from '@/lib/types';
import { format } from 'date-fns';

export default function ViewReportPage() {
    const params = useParams();
    const router = useRouter();
    const id = typeof params.id === 'string' ? params.id : '';
    const firestore = useFirestore();

    const reportRef = useMemoFirebase(() => doc(firestore, 'generated_reports', id), [firestore, id]);
    const { data: report, isLoading } = useDoc<GeneratedReport>(reportRef);

    if (isLoading) {
        return (
            <div className="flex h-screen items-center justify-center">
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Loading report...
            </div>
        );
    }

    if (!report) {
        notFound();
        return null;
    }
    
    const formatDate = (timestamp: any) => {
        if (!timestamp) return 'N/A';
        if (timestamp.seconds) {
            return format(new Date(timestamp.seconds * 1000), 'yyyy-MM-dd HH:mm');
        }
        return 'Invalid Date';
    }


    return (
        <div className="max-w-4xl mx-auto p-4 sm:p-8">
            <div className="flex justify-end mb-4 gap-2 print:hidden">
                 <Button onClick={() => router.back()} variant="outline">
                    <ArrowLeft className="mr-2 h-4 w-4" />
                    Back to History
                </Button>
                <Button onClick={() => window.print()}>
                    <Printer className="mr-2 h-4 w-4" /> Print / Save PDF
                </Button>
            </div>
            <Card className="p-8 shadow-lg">
                <CardHeader>
                    <CardTitle>Weekly Report: {report.startDate} to {report.endDate}</CardTitle>
                    <CardDescription>
                        Generated by {report.generatedByUserName} on {formatDate(report.generatedAt)}
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="p-4 bg-muted rounded-md border font-mono text-sm whitespace-pre-wrap">
                        {report.reportText}
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
