'use client';

import { useParams, notFound, useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Loader2, ArrowLeft, Printer } from 'lucide-react';
import { useDoc, useFirestore, useMemoFirebase } from '@/firebase';
import { doc } from 'firebase/firestore';
import type { GeneratedReport } from '@/lib/types';
import { format } from 'date-fns';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export default function ViewReportPage() {
    const params = useParams();
    const router = useRouter();
    const id = typeof params.id === 'string' ? params.id : '';
    const firestore = useFirestore();

    const reportRef = useMemoFirebase(() => doc(firestore, 'generated_reports', id), [firestore, id]);
    const { data: report, isLoading } = useDoc<GeneratedReport>(reportRef);

    if (isLoading) {
        return (
            <div className="flex h-screen items-center justify-center">
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Loading report...
            </div>
        );
    }

    if (!report) {
        notFound();
        return null;
    }
    
    const formatDate = (timestamp: any) => {
        if (!timestamp) return 'N/A';
        if (timestamp.seconds) {
            return format(new Date(timestamp.seconds * 1000), 'yyyy-MM-dd HH:mm');
        }
        return 'Invalid Date';
    }

    const shareUrl = typeof window !== 'undefined' ? window.location.href : '';
    const shareText = `Report generated for period ${report.startDate} to ${report.endDate}\n${shareUrl}`;

    return (
        <div className="max-w-4xl mx-auto p-4 sm:p-8">
            <style>{'@media print { @page { size: portrait; margin: 0; } body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } .print\\:hidden { display: none !important; } }'}</style>
            <div className="flex flex-wrap justify-end mb-4 gap-2 print:hidden">
                 <Button onClick={() => router.back()} variant="outline">
                    <ArrowLeft className="mr-2 h-4 w-4" />
                    Back to History
                </Button>
                
                <Button 
                  variant="default" 
                  className="gap-2"
                  onClick={(e) => {
                    e.preventDefault(); 
                    window.print();
                  }}
                >
                  <Printer className="h-4 w-4" />
                  Save as PDF / Print
                </Button>
            </div>
            <Card className="shadow-lg border-0 print:shadow-none bg-transparent">
                <CardHeader className="print:hidden bg-white border rounded-t-xl mb-4">
                    <CardTitle>Report generated for period {report.startDate} to {report.endDate}</CardTitle>
                    <CardDescription>
                        Generated by {report.generatedByUserName} on {formatDate(report.generatedAt)}
                    </CardDescription>
                </CardHeader>
                <CardContent className="p-0">
                    <div className="bg-white p-8 md:p-12 border shadow-sm print:shadow-none print:border-none min-h-[29.7cm] mx-auto max-w-[21cm]">
                        <div className="flex justify-between items-center border-b-2 border-slate-800 pb-6 mb-8">
                            <div className="w-1/3">
                            <img src="/Altek-Logo.jpeg" alt="Altek Green Logo" className="h-20 w-auto object-contain" />
                            </div>
                            <div className="text-right text-[10px] text-slate-600 space-y-1 font-sans">
                            <h2 className="text-xl font-black text-slate-900 uppercase tracking-tighter">ALTEK GREEN (PTY) LTD</h2>
                            <div className="space-y-0">
                                <p>9A Langwa Street, Strijdom Park</p>
                                <p>Randburg, 2194</p>
                            </div>
                            </div>
                        </div>
                        <ReactMarkdown
                            remarkPlugins={[remarkGfm]}
                            className="space-y-6 font-sans text-slate-800 leading-relaxed"
                            components={{
                            h1: () => null,
                            h2: ({ node, ...props }) => (
                                <h2 className="text-lg font-bold text-slate-900 mt-8 mb-4 border-b border-slate-300 pb-1 break-after-avoid" {...props} />
                            ),
                            h3: ({ node, ...props }) => (
                                <h3 className="text-base font-bold text-slate-800 mt-6 mb-2 underline decoration-slate-400 underline-offset-4" {...props} />
                            ),
                            ul: ({ node, ...props }) => (
                                <ul className="list-disc list-outside pl-6 space-y-2 mb-4 text-slate-700 text-sm" {...props} />
                            ),
                            p: ({ node, ...props }) => (
                                <p className="mb-4 text-justify text-xs md:text-sm" {...props} />
                            ),
                            table: ({ node, ...props }) => (
                                <div className="overflow-x-auto my-6 border rounded-lg">
                                <table className="min-w-full border-collapse text-[10px] md:text-xs" {...props} />
                                </div>
                            ),
                            thead: ({ node, ...props }) => <thead className="bg-slate-100" {...props} />,
                            th: ({ node, ...props }) => (
                                <th className="border-b border-slate-300 px-4 py-2 text-left font-bold text-slate-900 uppercase tracking-wider" {...props} />
                            ),
                            td: ({ node, ...props }) => (
                                <td className="border-b border-slate-200 px-4 py-2 text-slate-700 align-top" {...props} />
                            ),
                            }}
                        >
                            {report.reportText}
                        </ReactMarkdown>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
